/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.usfirst.team2077.intro;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
}
