/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.usfirst.team2077.intro;

import java.util.*;

public class App {
    private static String readLine(Scanner scanner) {
        return scanner.nextLine();
    }

    public static void main(String[] args) {
        String aNumber = "165.34";
        try {
            int number = Integer.parseInt(aNumber, 10);
        } catch(NumberFormatException e) {
            System.err.println("We failed to parse integer: " + e.getMessage());
        }

        try {
            double number = Double.parseDouble(aNumber);
        } catch(NumberFormatException e) {
            System.err.println("We failed to parse double: " + e.getMessage());
        }

        try(Scanner scanner = new Scanner(System.in)) {
            System.out.println("Give me a list (CSV):");

            String line = readLine(scanner);
            Items items = new Items(line);

            System.out.println();
            items.printItems();
            System.out.println();
            System.out.println(Arrays.toString(items.items()));

            System.out.println();
            System.out.println("Bye!");
        }
    }
}
